services:
  - type: web
    name: newspaper-ai
    env: node
    buildCommand: |
      npm install && NODE_ENV=production npx tsc && NODE_OPTIONS="--max_old_space_size=3072" npx vite build || node build-fallback.js
    startCommand: node server.js
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "18.20.8"
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: newspaper-ai
          envVarKey: PORT
        default: 10000
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_OPENROUTER_API_KEY
        sync: false
      - key: VITE_THENEWSAPI_KEY
        sync: false
      - key: VITE_NEWSDATA_KEY
        sync: false
      - key: VITE_NEWSAPI_KEY
        sync: false
      - key: VITE_APITUBE_KEY
        sync: false
      - key: VITE_RADAR_PUBLISHABLE_KEY
        sync: false
      - key: VITE_GOOGLE_API_KEY
        sync: false
      - key: VITE_GOOGLE_SEARCH_ENGINE_ID
        sync: false
      - key: VITE_GOOGLE_OAUTH_CLIENT_ID
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Cache-Control
        value: "public, max-age=31536000" 