services:
  - type: web
    name: newspaper-ai
    env: node
    buildCommand: |
      npm install && NODE_ENV=production npm run build || node build-fallback.js
    startCommand: NODE_ENV=production node server.js
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "18.20.8"
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: newspaper-ai
          envVarKey: PORT
        default: 10000
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_OPENROUTER_API_KEY
        sync: false
      - key: VITE_THENEWSAPI_KEY
        sync: false
      - key: VITE_NEWSDATA_KEY
        sync: false
      - key: VITE_NEWSAPI_KEY
        sync: false
      - key: VITE_APITUBE_KEY
        sync: false
      - key: VITE_RADAR_PUBLISHABLE_KEY
        sync: false
      - key: VITE_GOOGLE_API_KEY
        sync: false
      - key: VITE_GOOGLE_SEARCH_ENGINE_ID
        sync: false
      - key: VITE_GOOGLE_OAUTH_CLIENT_ID
        sync: false 