services:
  - type: web
    name: newspaper-ai
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: newspaper-ai
          envVarKey: PORT
        default: 10000
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_OPENROUTER_API_KEY
        sync: false
      - key: VITE_NEWS_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: "public, max-age=3600"
      - path: /assets/*
        name: Cache-Control
        value: "public, max-age=31536000" 